### PR TITLE
Use zh-TW for name of Hong Kong

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Thankns @Mangoov pointsout where to change this!

Fixes https://github.com/Shopify/internationalization-issues/issues/241

After this, needs to bump version and update this gem in core.

### CODE REVIEW

**Review by Mangoov — COMMENTED** [review]
The change should be done in `rails/locale/iso_639-1/zh-HK.yml` file no?

**Comment by JuanitoFatas** [comment]
> The change should be done in `rails/locale/iso_639-1/zh-HK.yml` file no?

screenshot_2018-09-26_20_53_55

In the example shop from reported issue, the checkout is using `zh` locale.

**Comment by Mangoov** [comment]
hm... That seems weird to me, I reading Frankie's description again the merchant said they were in `zh-HK` but the value for HK in that locale is just `香港`

I wonder if there's a fallback problem OR if they just have the wrong configuration.

I don't think we should be changing it to Traditional for baseline ZH

**Comment by JuanitoFatas** [comment]
> I don't think we should be changing it to Traditional for baseline ZH
👍 


> I wonder if there's a fallback problem OR if they just have the wrong configuration.

They need to specify `zh-HK` for the checkout redirect link instead of `zh`:

screenshot 2018-09-26 21 06 02

**Pull request closed without merging**
