### PR TITLE
Add province translations

### PR DESCRIPTION
**Pull request by Mangoov**
This PR adds Province translations.

The caveat is that we won't be able to handle english fallback for now.
This PR raises that question, should the translations be in an `en.yml` file or should we rely directly on the name provided from the country records in CountryDb

### CODE REVIEW

**Review by goldenson — COMMENTED** [review]
I think it will make more sense to handle translations in separate files.

Translation over Configuration 😄

**Comment by nimzco** [comment]
@goldenson You mean one file that translate countries and one provinces or one per country?
Probably not the latter I'd say.

**Comment by goldenson** [comment]
@nimzco Yep not 💯 sure this is the right solution but I think that's part of our recommendations

**Review by nimzco — APPROVED** [review]
I'm fine to ship this as is and reorganize files in an other PR. 👍 🐑

**Comment by nimzco** [comment]
> This PR raises that question, should the translations be in an en.yml file or should we rely directly on the name provided from the country records in CountryDb

I'd only rely on these translations, therefore always have a defaults in the `en.yml`.

**Pull request merged**
